// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aztaqiacvdpjhzoeddls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6dGFxaWFjdmRwamh6b2VkZGxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MzQ2ODIsImV4cCI6MjA2NzIxMDY4Mn0.rZk93mYkV0_vAmU4sAwHprdvOza3aI6AWWrTgtXg6vA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});